export interface EnvironmentVariables {
  VALIDATE_VIDEO_WORKER_PORT: number;
  MAX_VIDEO_SIZE_IN_BYTES: number;
  RABBIT_MQ_VIDEO_TOUCH_TOPIC_EXCHANGE: string;
  RABBIT_MQ_VALIDATE_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_VALIDATE_VIDEO_QUEUE: string;
  RABBIT_MQ_UPDATE_ASSET_ROUTING_KEY: string;
  RABBIT_MQ_UPDATE_ASSET_STATUS_ROUTING_KEY: string;
  RABBIT_MQ_URL: string;
  TEMP_VIDEO_DIRECTORY: string;
}
