export interface EnvironmentVariables {
  API_PORT: number;
  APP_NAME: string;

  SWAGGER_TITLE: string;
  SWAGGER_DESCRIPTION: string;
  SWAGGER_VERSION: string;
  SWAGGER_SERVER_BASE_URL: string;
  SWAGGER_SERVER_BASE_URL_DESCRIPTION: string;

  SWAGGER_USERNAME: string;
  SWAGGER_PASSWORD: string;
  DB_DRIVER: string;
  DB_USER: string;
  DB_PASSWORD: string;
  DB_NAME: string;
  DB_HOST: string;
  DB_PORT: number;
  DB_MIGRATE: string;

  RABBIT_MQ_URL: string;
  RABBIT_MQ_VIDEO_TOUCH_TOPIC_EXCHANGE: string;
  RABBIT_MQ_UPDATE_ASSET_STATUS_ROUTING_KEY: string;
  RABBIT_MQ_UPDATE_ASSET_STATUS_QUEUE: string;
  RABBIT_MQ_UPDATE_FILE_STATUS_ROUTING_KEY: string;
  RABBIT_MQ_UPDATE_FILE_STATUS_QUEUE: string;
  RABBIT_MQ_UPDATE_ASSET_ROUTING_KEY: string;
  RABBIT_MQ_UPDATE_ASSET_QUEUE: string;
  MAX_VIDEO_SIZE_IN_BYTES: number;

  BULL_VALIDATE_JOB_QUEUE: string;
  BULL_DOWNLOAD_JOB_QUEUE: string;
  BULL_UPLOAD_JOB_QUEUE: string;
  BULL_360P_PROCESS_VIDEO_JOB_QUEUE: string;
  BULL_480P_PROCESS_VIDEO_JOB_QUEUE: string;
  BULL_540P_PROCESS_VIDEO_JOB_QUEUE: string;
  BULL_720P_PROCESS_VIDEO_JOB_QUEUE: string;
  BULL_1080P_PROCESS_VIDEO_JOB_QUEUE: string;
  BULL_THUMBNAIL_GENERATION_JOB_QUEUE: string;

  AWS_ACCESS_KEY_ID: string;
  AWS_REGION: string;
  AWS_SECRET_ACCESS_KEY: string;
  AWS_S3_BUCKET_NAME: string;
  VIDEO_BASE_URL: string;

  TEMP_UPLOAD_DIRECTORY: string;
  TEMP_VIDEO_DIRECTORY: string;

  CDN_BASE_URL: string;

  DEFAULT_THUMBNAIL_URL: string;
  JWT_EXPIRATION_TIME_IN_SEC: number;
  JWT_SECRET: string;
  REDIS_HOST: string;
  REDIS_PORT: number;
  MIN_AVAILABLE_DISK_SPACE_REQUIRED_IN_BYTES: number;
  RETRY_JOB_ATTEMPT_COUNT: number;
  RETRY_JOB_BACKOFF_IN_MINUTE: number;
}
