export interface EnvironmentVariables {
  PORT: number;

  SWAGGER_TITLE: string;
  SWAGGER_DESCRIPTION: string;
  SWAGGER_VERSION: string;
  SWAGGER_SERVER_BASE_URL: string;
  SWAGGER_SERVER_BASE_URL_DESCRIPTION: string;

  SWAGGER_USERNAME: string;
  SWAGGER_PASSWORD: string;
  DB_DRIVER: string;
  DB_USER: string;
  DB_PASSWORD: string;
  DB_NAME: string;
  DB_HOST: string;
  DB_PORT: number;
  DB_MIGRATE: string;

  RABBIT_MQ_URL: string;
  RABBIT_MQ_VIDEO_TOUCH_TOPIC_EXCHANGE: string;
  RABBIT_MQ_DOWNLOAD_VIDEO_QUEUE: string;
  RABBIT_MQ_DOWNLOAD_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_VALIDATE_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_VALIDATE_VIDEO_QUEUE: string;
  MAX_VIDEO_SIZE_IN_BYTES: number;

  RABBIT_MQ_1080P_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_1080P_VIDEO_QUEUE: string;
  RABBIT_MQ_720P_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_720P_VIDEO_QUEUE: string;
  RABBIT_MQ_540P_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_540P_VIDEO_QUEUE: string;
  RABBIT_MQ_480P_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_480P_VIDEO_QUEUE: string;
  RABBIT_MQ_360P_VIDEO_ROUTING_KEY: string;
  RABBIT_MQ_360P_VIDEO_QUEUE: string;
}
