export interface EnvironmentVariables {
  AUDIO_WORKER_PORT: number;
  RABBIT_MQ_VIDEO_TOUCH_TOPIC_EXCHANGE: string;
  RABBIT_MQ_UPDATE_FILE_STATUS_ROUTING_KEY: string;
  RABBIT_MQ_URL: string;
  TEMP_VIDEO_DIRECTORY: string;
  BULL_AUDIO_EXTRACTION_JOB_QUEUE: string;
  BULL_UPLOAD_JOB_QUEUE: string;
  BULL_AUDIO_TRANSCRIPTION_JOB_QUEUE: string;
  REDIS_HOST: string;
  REDIS_PORT: number;
  TRANSCRIPTION_GENERATION_ENABLED: boolean;
  GOOGLE_GEN_AI_MODEL: string;
  GOOGLE_GENAI_API_KEY: string;
  OPENAI_MODEL: string;
  OPENAI_API_KEY: string;
}
