export const VIDEO_STATUS = {
  QUEUED: 'QUEUED',
  DOWNLOADING: 'DOWNLOADING',
  DOWNLOADED: 'DOWNLOADED',
  VALIDATED: 'VALIDATED',
  PROCESSING: 'PROCESSING',
  FAILED: 'FAILED',
  READY: 'READY'
};